logging:
  level:
    com:
      dev: DEBUG

server:
  servlet:
    session:
      timeout: 86400
      maximum-sessions: 1
      max-sessions-prevents-login: false
  ssl:
    key-store: C:\projects\run\keystore.p12